services:
  - type: web
    name: pwm-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pwm-db
          property: connectionString
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: pwm-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: pwm-db
          property: password
databases:
  - name: pwm-db
    plan: free
