server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
